### PR TITLE
Add Paket as a known UserAgentClient

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by forki** [comment]
Very cool. Thanks for merging. Do you have an ETA for when this would go to nuget.org?

**Comment by xavierdecoster** [comment]
Thx for the PR!
In terms of ETA, aiming for ASAP :) Will update the thread when it's live.

**Comment by forki** [comment]
any news on this?

**Comment by xavierdecoster** [comment]
@forki the changes from your PR are live already, but we have an issue with one of the jobs processing stats. @bhuvak is looking into this.

**Comment by forki** [comment]
I was a bit worried that my change was incorrect since there is no way to test it for me.

https://www.nuget.org/stats/packages/FAKE?groupby=ClientName should show lot's of paket downloads

**Comment by yishaigalatzer** [comment]
Xavier if this is life why is the pr still open?

Forki - we are looking at fixing the stats as second priority to bringing the stability of the site up. This will get updated eventually.

**Comment by xavierdecoster** [comment]
@yishaigalatzer PR is merged 15 days ago :)

**Comment by forki** [comment]
So the statistics are not updated anymore? https://www.nuget.org/stats/packages/FAKE?groupby=ClientName seems to be static for a very long time.

**Comment by xavierdecoster** [comment]
@forki already [acknowledged 8 days ago](https://github.com/NuGet/NuGet.Warehouse/pull/5#issuecomment-107226083) in reply to your previous question :) It's on our shortlist of things to fix asap, though it has a lower priority in favor of fixing stability and resilience issues encountered in the past weeks.

**Comment by forki** [comment]
Sorry. "we have an issue with one of the jobs processing stats" - I didn't read that as it's completely gone. ;-)

**Comment by forki** [comment]
ping. https://www.nuget.org/stats/packages/FAKE?groupby=ClientName is now showing 4 months old data.

**Comment by yishaigalatzer** [comment]
Working with @maartenba on the release blog, and finalizing the testing. Bare with us for a few more.

**Comment by maartenba** [comment]
@forki, FYI: we have a pre-production version up at http://nuget-preprod-0-v2gallery.cloudapp.net/ which we want to test for a few more days. Feel free to click around and let us know any quirks you may see. Reports there are generated from production traffic every few hours now (instead of every 24 hours in the old days).

(on a side note, stats are slightly different from what you see on NuGet.org - we now also have DNX downloads tracked and some other user agents (mostly crawlers) are no longer tracked)

**Comment by forki** [comment]
thx. looks good so far. unfortunately there is still (unknown) as the biggest client in any chart.

**Comment by maartenba** [comment]
Browsers, DNX (which is not sending a user agent) and others.

**Comment by yishaigalatzer** [comment]
Maarten - can we add browsers as a category?

Sent from my Windows Phone
________________________________

**Comment by forki** [comment]
yes. at least try to minizime the "(unknown)". Also please ask the DNX
people to send a user agent.

2015-09-01 15:52 GMT+02:00 Yishai Galatzer <notifications@github.com>:

**Comment by yishaigalatzer** [comment]
They are sending it starting from the next beta.

Sent from my Windows Phone
________________________________

**Comment by maartenba** [comment]
@yishaigalatzer Would that category be simple "Browsers" or do we want more details?

**Comment by yishaigalatzer** [comment]
Browsers sounds good enough

Sent from my Windows Phone
________________________________

**Comment by forki** [comment]
this sounds strange. Why are browsers the most common agent? Bots?

2015-09-01 16:20 GMT+02:00 Yishai Galatzer <notifications@github.com>:

**Comment by maartenba** [comment]
Looking into the unknowns. No conclusions on what the majority is. Yet.

**Comment by maartenba** [comment]
On to something, we may have to re-parse all user agents again.

**Comment by forki** [comment]
exciting ;-)

2015-09-01 18:42 GMT+02:00 Maarten Balliauw <notifications@github.com>:

**Comment by yishaigalatzer** [comment]
Hooray for staging environment and making them public to caring users
________________________________

**Comment by maartenba** [comment]
Plus I get to play with some big VM's again! #ftw

**Comment by maartenba** [comment]
Woohoo! All re-parsed. Look at that Paket fly! http://nuget-preprod-0-v2gallery.cloudapp.net/stats/packages/FAKE?groupby=ClientName

The unknowns you see now are:
* curl and wget
* Ruby clients downloading packages
* Java clients downloading packages
* Actual empty/unknown user agents (includes DNX up until their newest betas)

If desired we can filter them out from the generated stats, but then again: they are valid package downloads.

**Comment by forki** [comment]
Wow. Cool and that's what I actually expected. At least for FAKE I assumed
that many users switched to paket.

**Pull request merged**
